Specify some steps in the release flow
SenseNet/sn-resources pull request #85
Opened 2020-12-10 10:50 UTC by pusztaienike

2020-12-14 19:48 UTC, herflis requested changes

2020-12-14 19:48 UTC, herflis commented on docs/gitflow/gitflow.md
> +- Audit the netlify build with [Lighthouse](https://developers.google.com/web/tools/lighthouse#devtools), check for regressions, compare it with previous result
```suggestion
- Audit the netlify build with [Lighthouse](https://developers.google.com/web/tools/lighthouse#devtools), check for regressions, compare it with previous results
```

2020-12-14 19:48 UTC, herflis commented on docs/gitflow/gitflow.md
> +- Check [relativeCI](https://app.relative-ci.com/projects/SpRCK0ViJsBVzSUtpFtk) for bundle size changes, compare it with the previous. Please attach the result to the description of the release PR.
```suggestion
- Check [relativeCI](https://app.relative-ci.com/projects/SpRCK0ViJsBVzSUtpFtk) for bundle size changes, compare it with the previous. Please attach results to the description of the release PR.
```

2020-12-14 19:48 UTC, herflis commented on docs/gitflow/gitflow.md
>  Release
```suggestion
Test
```

2020-12-14 19:48 UTC, herflis commented on docs/gitflow/gitflow.md
>  Staging
```suggestion
Release/Staging
```

2020-12-15 09:11 UTC, herflis approved these changes

2021-01-13 14:20 UTC, taki9 commented on docs/gitflow/gitflow.md
> +- _staging_: temporary branch for each release, used for creating near production QA environment with released backend
- _staging_: temporary branch for each release, used for creating near production QA environment with released backend
```suggestion
- _release_: temporary branch for each release, used for creating near production QA environment with released backend
```

2021-01-13 14:20 UTC, taki9 commented on docs/gitflow/gitflow.md
> +- Frontend: https://admin.test.sensenet.com/ - _master_ - built daily
develop branch, maybe on push?

2021-01-13 14:20 UTC, taki9 commented on docs/gitflow/gitflow.md
> +- Backend: https://netcore-service.test.sensenet.com/ - _master_ branch - built daily
develop I think

2021-01-13 14:20 UTC, taki9 commented on docs/gitflow/gitflow.md
> -* Frontend: https://admin.test.sensenet.com/ - *master* - built daily
release environment is admin.sensenet.com
builds on master push?

2021-01-18 09:00 UTC, taki9 approved these changes

2021-01-18 09:35 UTC, merged